### ISSUE TITLE
visuals.plot_2d ignores boolean flags

### ISSUE THREAD

**Issue by NickOrtega616** [root-11/graph-theory#20]
The function just needs to nest those parts of the code inside if statements as is done in plot_3d.

**Comment by root-11** [comment]
So that these two variables are in both func signatures: `rotation='xyz', maintain_aspect_ratio=False` ?
![image](https://user-images.githubusercontent.com/4048422/95080140-8c056600-070f-11eb-886a-394d9f50e06e.png)

**Comment by root-11** [comment]
@NickOrtega616 ?

**Comment by fiendish** [comment]
NickOrtega616 appears to be talking about plot_2d not actually using its nodes and edges arguments.
There's no equivalent in plot_2d of https://github.com/root-11/graph-theory/blob/3ebf1b2c1ce1c6afe66e6f5e1bff512dc6db7a00/graph/visuals.py#L96 and https://github.com/root-11/graph-theory/blob/3ebf1b2c1ce1c6afe66e6f5e1bff512dc6db7a00/graph/visuals.py#L106

**Comment by root-11** [comment]
Addressed in bf7d6e1cf5

**Comment by NickOrtega616** [comment]
Sorry for the delayed reply. Yes, this commit exactly addresses my questions.

**Comment by root-11** [comment]
Packaged in https://pypi.org/project/graph-theory/2020.11.4.41115/
