### ISSUE TITLE
The lru cache on is_connected causes invalid results if new edges are added

### ISSUE THREAD

**Issue by fiendish** [root-11/graph-theory#21]
Adding new edges has to clear the cache, otherwise you get:

```Python
>>> from graph import Graph
>>> a = Graph()
>>> a.is_connected(1, 2)
False
>>> a.add_edge(1, 2)
>>> a.is_connected(1, 2)
False
```

**Comment by fiendish** [comment]
Also it's not documented that is_connected has an lru cache on it, so one would never know that the cache needs to be flushed unless examining the internal code.

**Comment by root-11** [comment]
+1. Shall we remove it?

**Comment by fiendish** [comment]
Probably remove it. If someone wants to cache results, they can always do it externally.

**Comment by root-11** [comment]
`phaselines` requires some form of caching to work effectively. Proposal is in [branch lru_cache](https://github.com/root-11/graph-theory/compare/lru_cache). Please review.

**Comment by fiendish** [comment]
I added some comments on the branch.
