### ISSUE TITLE
graph.Graph.shortest_path gives incorrect output with weighted graphs when using memoize=True

### ISSUE THREAD

**Issue by CodeMartyLikeYou** [root-11/graph-theory#24]
Code:
`import graph`
`g = graph.Graph()`
`g.add_edge(1, 2, 3, False)`
`g.add_edge(2, 3, 4, False)`
`g.add_edge(1, 3, 10, False)`
`print(g.shortest_path(1, 3, memoize=True))`

Expected output: 
`(7, [1, 2, 3])`

Actual output:
`(10, [1, 3])`

**Comment by root-11** [comment]
Yep. The most direct connection cannot be guaranteed to be the shortest path.
Solved in https://github.com/root-11/graph-theory/commit/620fff621052c223d1073800d7d839d549f4a82f packaged to pypi as [2021.2.10.33370](https://pypi.org/project/graph-theory/2021.2.10.33370/)

Use `pip install graph-theory --upgrade --no-cache` to update.

**Comment by root-11** [comment]
@CodeMartyLikeYou credits in the readme to you ;-)

**Comment by CodeMartyLikeYou** [comment]
Thanks for the quick fix!
