### ISSUE TITLE
Deleting a node doesn't fully eliminate it from the graph

### ISSUE THREAD

**Issue by haxsaw** [root-11/graph-theory#25]
It appears that when you delete a node, certain traces of it are left behind in the graph's internal bookkeeping structures.

Consider this simple graph:
```python
g = graph.Graph()
g.add_edge(1, 3)
g.add_edge(2, 3)
```
If we now try to do a topological sort on it by iteratively finding the edges with in_degree=0:
```python
the_sort = []

zero_in = g.nodes(in_degree=0)
while zero_in:
    for n in zero_in:
        the_sort.append(n)
        g.del_node(n)
    zero_in = g.nodes(in_degree=0)
    print(f"remaining nodes: {len(g.nodes())},"
          f" in_degree=0 nodes: {len(g.nodes(in_degree=0))}")
```
...this loop will never terminate. The remaining nodes will be reported as 0 (`len(g.nodes())`), however there will
remain nodes in the graph with in_degree=0 (`len(g.nodes(in_degree=0))`). When looking at the code, it appears to
be a problem with the accounting done in `del_edge()`; `self._in_degree[node2]` is decremented, but the dict entry
probably should be deleted if `self._out_degree[node2]` is zero as well. However, since `del_edge()` is a public method,
it might be the case that having a floating node with no inbound or outbound edges is totally acceptable, in which case
you might need something else to decide when to actually get rid of the entry for a deleted node in these two dicts.

**Comment by root-11** [comment]
Hi Tom,
In my last release I accelerated the shortest path algorithms and added a data structure to support this. 
It worked, but I missed a logical path on del_edge - which you found! Thanks for this. 

I've updated pypi with [version 2021.3.27.73763](https://pypi.org/project/graph-theory/), added the credits to you and I've added topological sort as well.
Thank you!
