### ISSUE TITLE
`__eq__` (equality) can in some cases return false for two identical graphs

### ISSUE THREAD

**Issue by Sappique** [root-11/graph-theory#41]
In some cases the private `_edges` of a graph can gain an empty dict as a entry. This leads to incorrect behavior when comparing graphs.
This bug is very similar to #40.

### To reproduce
```python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
>>> from graph import Graph
>>> g1 = Graph(from_list=[(1,2),(2,3)])
>>> g2 = Graph(from_list=[(1,2),(2,3)])
>>> g1.edge(3,1)
>>> g1 == g2
False
>>> g1._edges
defaultdict(<class 'dict'>, {1: {2: 1}, 2: {3: 1}, 3: {}})
>>> g2._edges
defaultdict(<class 'dict'>, {1: {2: 1}, 2: {3: 1}})
```

### Cause
The equality function of graphs compares the private variable `_edges` of both graphs and if they are not equal, the function returns false.
The variable `_edges` can in some cases be accessed with keys that don't exist, since it is a `defaultdict(dict)` in those cases a empty `dict` is created for that key. If that happens with only one of two identical graphs, they are no longer equal.
The accessing of `_edges` with not existing keys and thus the creation of a new entry can occur when `edge(node1, node2)` is called with a `node1` without outgoing edges or sometimes when `is_connected(n1, n2)` is called depending on the graph. Those are the two examples I found, there could be more.

### Other problems
Just like with #40 this also causes strange behavior when copying graphs, because `copy()` uses the public edge getter `edges()` instead of the private variable `_edges`.
```python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
>>> from graph import Graph
>>> g1 = Graph(from_list=[(1,2),(2,3)])
>>> g1.edge(3,1)
>>> g2 = g1.copy()
>>> g1 == g2
False
>>> g1._edges
defaultdict(<class 'dict'>, {1: {2: 1}, 2: {3: 1}, 3: {}})
>>> g2._edges  
defaultdict(<class 'dict'>, {1: {2: 1}, 2: {3: 1}})
```

### Additional information
I'm using version 2023.7.6 of graph-theory with Python 3.10 on windows.

**Comment by root-11** [comment]
Thank you so much for the write-up @Sappique. This is a role-model bug report. Excellent work!

I have added your tests in a9be334ea0615a1d2662e60eca3b9438efc0ca38 and added the bugfix in 58d78ac0d8fd00b3cd65d1a222dee96779886ab1 . 

The [release 2023.7.7](https://pypi.org/project/graph-theory/2023.7.7/) is now on pypi.org thanks to you.
